# Generated by Django 5.0.4 on 2024-05-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyetrack', '0002_gazetrackingresultnew_delete_gazetrackingresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GazeTrackingResultNew',
            new_name='GazeTrackingResult',
        ),
    ]
