# Generated by Django 5.0.4 on 2024-06-15 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyetrack', '0004_gazetrackingresult_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gazetrackingresult',
            name='interview_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gazetrackingresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
